language: scala

scala:
  - 2.10.6

script: sbt ++$TRAVIS_SCALA_VERSION pipeline

before_deploy:
  - mkdir -p $HOME/.bintray
  - openssl aes-256-cbc -K $encrypted_e896445c48a3_key -iv $encrypted_e896445c48a3_iv -in .credentials.enc -out $HOME/.bintray/.credentials -d

deploy:
  provider: script
  script: sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    branch: master

jdk:
  - oraclejdk8
